name: Android CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 1.11
        uses: actions/setup-java@v1
        with:
          java-version: 1.11
      - name: set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Decrypt google-services.json
        env: # Or as an environment variable
          google_services_key: ${{ secrets.GOOGLE_SERVICES_KEY }}
        run: openssl aes-256-cbc -k $google_services_key -pbkdf2 -in voipms-sms/src/primary/google-services.json.enc -out voipms-sms/src/primary/google-services.json -d
      - name: Build with Gradle
        run: ./gradlew build
